# Generated by Django 2.2.7 on 2019-11-14 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format_name', models.CharField(max_length=200)),
                ('format_symbol', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Swift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('topic_on', models.CharField(max_length=20)),
                ('topic_off', models.CharField(max_length=20)),
                ('message_info', models.CharField(max_length=200, null=True)),
                ('message_on', models.CharField(max_length=200, null=True)),
                ('message_off', models.CharField(max_length=200, null=True)),
                ('message_danger', models.CharField(max_length=200, null=True)),
                ('topic', models.CharField(max_length=200)),
                ('topic_check', models.CharField(max_length=200)),
                ('topic_check_on', models.CharField(max_length=20)),
                ('topic_check_off', models.CharField(max_length=20)),
                ('notify_users', models.CharField(max_length=1000, null=True)),
                ('create_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
                ('format_swift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uberserver.Format')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uberserver.Link')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uberserver.Type')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('condition_min', models.IntegerField()),
                ('condition_max', models.IntegerField()),
                ('message_info', models.CharField(max_length=200, null=True)),
                ('message_ok', models.CharField(max_length=200, null=True)),
                ('message_alarm', models.CharField(max_length=200, null=True)),
                ('message_danger', models.CharField(max_length=200, null=True)),
                ('topic', models.CharField(max_length=200)),
                ('notify_users', models.CharField(max_length=1000, null=True)),
                ('create_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
                ('format_sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uberserver.Format')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uberserver.Link')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uberserver.Type')),
            ],
        ),
    ]
