# Generated by Django 2.2.7 on 2019-11-15 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uberserver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='condition_max',
            field=models.IntegerField(help_text='Максимальные значения'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='condition_min',
            field=models.IntegerField(help_text='Минимальные значения'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='format_sensor',
            field=models.ForeignKey(help_text='Формат', on_delete=django.db.models.deletion.CASCADE, to='uberserver.Format'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='link',
            field=models.ForeignKey(help_text='Ссылка на объект', on_delete=django.db.models.deletion.CASCADE, to='uberserver.Link'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='message_alarm',
            field=models.CharField(help_text='Сигнальная информация', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='message_danger',
            field=models.CharField(help_text='Сообщение об аварии', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='message_info',
            field=models.CharField(help_text='Информация о сенсоре', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='message_ok',
            field=models.CharField(help_text='Когда все ок', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='name',
            field=models.CharField(help_text='Название', max_length=200),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='notify_users',
            field=models.CharField(help_text='Пользователи telegram', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='topic',
            field=models.CharField(help_text='Топик MQTT', max_length=200),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='type',
            field=models.ForeignKey(help_text='Тип', on_delete=django.db.models.deletion.CASCADE, to='uberserver.Type'),
        ),
        migrations.AlterField(
            model_name='swift',
            name='format_swift',
            field=models.ForeignKey(help_text='Формат', on_delete=django.db.models.deletion.CASCADE, to='uberserver.Format'),
        ),
        migrations.AlterField(
            model_name='swift',
            name='link',
            field=models.ForeignKey(help_text='Ссылка на объект', on_delete=django.db.models.deletion.CASCADE, to='uberserver.Link'),
        ),
        migrations.AlterField(
            model_name='swift',
            name='message_danger',
            field=models.CharField(help_text='Сообщение при неисправностях', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='swift',
            name='message_info',
            field=models.CharField(help_text='Информация о сенсоре', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='swift',
            name='message_off',
            field=models.CharField(help_text='Сообщение при выклчении', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='swift',
            name='message_on',
            field=models.CharField(help_text='Сообщение при вклчении', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='swift',
            name='name',
            field=models.CharField(help_text='Название', max_length=200),
        ),
        migrations.AlterField(
            model_name='swift',
            name='notify_users',
            field=models.CharField(help_text='Пользователи telegram', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='swift',
            name='topic',
            field=models.CharField(help_text='Топик MQTT', max_length=200),
        ),
        migrations.AlterField(
            model_name='swift',
            name='topic_check',
            field=models.CharField(help_text='Проверочный топик MQTT', max_length=200),
        ),
        migrations.AlterField(
            model_name='swift',
            name='topic_check_off',
            field=models.CharField(help_text="Значение 'off'", max_length=20),
        ),
        migrations.AlterField(
            model_name='swift',
            name='topic_check_on',
            field=models.CharField(help_text="Значение 'on'", max_length=20),
        ),
        migrations.AlterField(
            model_name='swift',
            name='topic_off',
            field=models.CharField(help_text="Значение 'off'", max_length=20),
        ),
        migrations.AlterField(
            model_name='swift',
            name='topic_on',
            field=models.CharField(help_text="Значение 'on'", max_length=20),
        ),
        migrations.AlterField(
            model_name='swift',
            name='type',
            field=models.ForeignKey(help_text='Тип', on_delete=django.db.models.deletion.CASCADE, to='uberserver.Type'),
        ),
    ]
