# Generated by Django 2.2.7 on 2019-11-15 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uberserver', '0002_auto_20191115_2056'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('telegram_id', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='notify_users',
        ),
        migrations.RemoveField(
            model_name='swift',
            name='notify_users',
        ),
        migrations.AddField(
            model_name='sensor',
            name='notify_users',
            field=models.ManyToManyField(help_text='Пользователи telegram', to='uberserver.TelegramUser'),
        ),
        migrations.AddField(
            model_name='swift',
            name='notify_users',
            field=models.ManyToManyField(help_text='Пользователи telegram', to='uberserver.TelegramUser'),
        ),
    ]
